services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/radarr:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped