version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
     - 9445:80 
    environment:
      DOMAIN: 
    volumes:
      - /srv/docker/vaultwarden:/data:rw