services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    volumes:
      - /srv/docker/heimdall:/config
    ports:
      - 8080:80
      - 4443:443
    restart: unless-stopped