---
version: "2.1"
services:
  rsnapshot:
    image: lscr.io/linuxserver/rsnapshot:latest
    container_name: rsnapshot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/appdata:/config
      - /path/to/snapshots:/.snapshots #optional
      - /path/to/data:/data #optional
    restart: unless-stopped
