---
version: "2.1"
services:
  series-troxide:
    image: lscr.io/linuxserver/series-troxide:latest
    container_name: series-troxide
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
